### ISSUE TITLE
Is this dead or is Model.Create([{},{}]) not as performant

### ISSUE THREAD

**Issue by XXChester** [greyblake/fast_seeder#1]
I came across this project and was looking for ways to speed up my seeding of new environments but looking over the homepage and source, I am not sure why creating a model in rails with an array of hashes wouldn't be equivalent?

If this was converting the input to raw SQL it would be faster but I do not see that happening. The one benefit I do see though, is with this approach you can have non-developers add seed files as they could do it in excel.

**Comment by greyblake** [comment]
@XXChester Hey, thanks for opening the issue.

This project is quite outdated you're right. I would recommend you to use activerecord-import: https://github.com/zdennis/activerecord-import instead.

I'll update README)
